VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.define "zookeeper1" do |zookeeper|
    zookeeper.vm.network :private_network, ip: "192.168.50.5"
    zookeeper.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
    zookeeper.vm.provision "shell", path: "provision-zookeeper.sh"
  end

  config.vm.define "kafka1" do |kafka|
    kafka.vm.network :private_network, ip: "192.168.50.20"
    kafka.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048"]
    end
    kafka.vm.provision "shell", path: "provision-kafka.sh", :args => "1"
  end

  config.vm.define "kafka2" do |kafka|
    kafka.vm.network :private_network, ip: "192.168.50.21"
    kafka.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048"]
    end
    kafka.vm.provision "shell", path: "provision-kafka.sh", :args => "2"
  end

  config.vm.define "kafka3" do |kafka|
    kafka.vm.network :private_network, ip: "192.168.50.22"
    kafka.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048"]
    end
    kafka.vm.provision "shell", path: "provision-kafka.sh", :args => "3"
  end  

end
